04-12-homework
Bartoszk236/Homework_Mentoring pull request #4
Opened 2024-12-08 14:25 UTC by Bartoszk236

2024-12-08 19:04 UTC, Y0ucandev requested changes

2024-12-08 19:04 UTC, Y0ucandev commented on src/classes/and/abstracts/methods/task1/Shape.java
> +abstract public class Shape {
w konwencji nazewniczej najpierw mamy modyfikator dostepu pozniej definiujemy czy klasa ma byc abstrakcyjna czy zwykla. tj public abstract class Shape

2024-12-08 19:04 UTC, Y0ucandev commented on src/classes/and/abstracts/methods/task2/Appliance.java
> +abstract public class Appliance {
popraw wszedzie to samo na co zwrocilem uwage wyzej

2024-12-08 19:04 UTC, Y0ucandev commented on src/classes/and/abstracts/methods/task3/Main.java
> +
zbedna pusta linia

2024-12-08 19:04 UTC, Y0ucandev commented on src/nested/classes/task16/Computer.java
> +    private Processor processor;
sprwadz kazdy plik i zachowaj jakis porzadek kodu. Pola w klasie maja byc na samej gorze. 
A Ty najpierw wprowadzasz prywatna klase wbudowana a na dole definiujesz pola klasy ktora jest klasa glowna. Nie jest to czytelne. Najpierw musza byc pola klasy potem konstrutkory metody i dopiero dalej cos.

2024-12-08 19:29 UTC, Bartoszk236 commented on src/nested/classes/task16/Computer.java
> +    private Processor processor;
Czyli najpierw klasa zewnętrzna pola, konstruktor, metody. Następnie klasa wewnętrzna pola, konstruktor metody?

2024-12-09 11:11 UTC, Y0ucandev approved these changes

2024-12-09 13:11 UTC, merged